name: robotframework

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - nodejs
  - pip

  - pip:
    - pytest
    - httpx
    - openai
    # - -e /workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat[browser_stealth]