[paths]

logo = "./static/logo.png"
robot = "/workspaces/CicloZero"
stock_excel = "/workspaces/CicloZero/downloads/stock"
price_excel = "/workspaces/CicloZero/downloads/price"

[configs]

[urls]
ocr = "http://nginx:80"

[theme]
base="dark"
primaryColor="#ffbd63"
backgroundColor="#000000"
secondaryBackgroundColor="#3f4a65"

[browser]
gatherUsageStats = false