[paths]

logo = "./static/logo.png"
ciclozero_logo = "./static/ciclozero_logo.png"
robot = "/workspaces/CicloZero"
stock_excel = "/workspaces/CicloZero/downloads/stock"
price_excel = "/workspaces/CicloZero/downloads/price"

[configs]

[urls]
ocr = "http://nginx:80"

[theme]
base="dark"
primaryColor="#7D7D7D"
backgroundColor="#111111"
secondaryBackgroundColor="#3f4a65"

[browser]
gatherUsageStats = false