version: '3.7'
services:

  playwright-chrome:
    image: playwright-chrome
    container_name: playwright-chrome
    init: true
    user: vscode
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080"]
      interval: 1s
      timeout: 10s
      retries: 3

  nginx_chrome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_chrome
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      playwright-chrome:
        condition: service_healthy

networks:
  default:
    driver: bridge

  