name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        eval $(minikube docker-env)
        docker build -f api/prod/Dockerfile -t api-orchestrator-image:latest api/

    # Cloudflare token must be stored in the machine
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f api/prod/deployment.yaml

    - name: Check Deployment Status
      run: |
        kubectl rollout restart api-orchestrator
        kubectl rollout status api-orchestrator
