name: base

channels:
  - defaults

dependencies:
  - python=3.10
  - pip

  - pip:
    - -e /workspaces/ai-butlerhat/data-butlerhat/robotframework-butlerhat
    - fastapi[all]
    - uuid
    - pydantic
    - logger