name: robotframework

channels:
  - default
  - conda-forge

dependencies:
  - python=3.10
  - nodejs
  - pip

  - pip:
    - robotframework-butlerhat[browser_stealth]
    - fastapi[all]
    - uuid
    - pydantic
    - logger