name: Build python package
on:
  push:
    branches: [ master ]
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Ofuscate phthon
      run: |
        pip install python-minifier
        pyminify ButlerRobot/ --in-place

    - name: Build Python package
      run: python setup.py sdist

    - name: Copy package to submodule directory
      run: |
        cp dist/*.tar.gz robotframework-dist-butlerhat/
        cd robotframework-dist-butlerhat/
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add latest package"
        git push

    - name: Upload Python package
      uses: actions/upload-artifact@v2
      with:
        name: butlerhat_package
        path: dist/*.tar.gz
