name: Push to PypiServer

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0  # Fetch all history for all tags and branches
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Ofuscate phthon
      run: |
        pip install python-minifier
        git checkout -b temp-build
        pyminify ButlerRobot/ --in-place
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Obfuscated Python for build"
        LATEST_TAG=$(git describe --tags --abbrev=0)
        echo "Latest tag is $LATEST_TAG"
        git tag -d $LATEST_TAG
        git tag $LATEST_TAG


    - name: Build Python package
      run: |
        git describe --tags --abbrev=0
        pip install setuptools_scm
        python setup.py sdist

    - name: Install Twine
      run: |
        python -m pip install twine
        
    - name: Upload Package to PyPI Server
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m twine upload --repository-url ${{ secrets.PYPISERVER }} dist/*.tar.gz

